### PR TITLE
Add work directory field

### PR DESCRIPTION
**Pull request by VBeatrice**

### CODE REVIEW

**Comment by VBeatrice** [comment]
The changes in this PR allow to specify a `work_directory` in which the `command` will be executed. The `input_files` field is still relative to the position of the `goldplate` file, the `stdout` field is relative to the work directory.

I found these changes useful for a command such as cabal that is sensitive to the work directory.

**Comment by jaspervdj-luminal** [comment]
Hi @VBeatrice, this is great!  Thanks a lot!

One thing I'm a little worried about is that the rules on how things work get a little complex (some things are relative, other things aren't).  I think it would be easier for users to remember if everything would be relative to the working directory.

On the other hand, I haven't used this yet so maybe there was a practical reason why you did things did way?

If not, I'm happy to take a stab at continuing from this code and seeing if it the end user experience can be made a bit more consistent.

**Comment by VBeatrice** [comment]
Hi @jaspervdj-luminal !

I did it that way mainly to preserve the original behavior, but I agree that having things relative to the `work_directory` (when it's specified) would be better as well as less confusing.  The last commit takes care of that. Please have a look at the builtin test, you may want to change it.

**Comment by VBeatrice** [comment]
Hey @jaspervdj-luminal , so do you think the changes in this PR could be integrated?

**Comment by jaspervdj-luminal** [comment]
Thanks a lot once more!  I renamed it to working directory since this terminology seems a bit more common.  Sorry for the delay in getting this merged.

**Pull request merged**
